services:
  - type: web
    name: unidownload
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    runtime: python
    region: oregon
    branch: main
    repo: https://github.com/himaanshuuyadav/UniDownload
